from sqlalchemy import (
    BigInteger,
    Column,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
METADATA = MetaData(naming_convention=NAMING_CONVENTION)


settings = Table(
    "settings",
    METADATA,
    Column("key", String(191), primary_key=True),
    Column("value", Text, nullable=False),
)

users = Table(
    "users",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("username", String(191), nullable=False),
    Column("password_hash", String(255), nullable=False),
    Column("role", String(32), nullable=False, server_default=text("'cashier'")),
    Column("active", Integer, nullable=False, server_default=text("1")),
    Column("last_login_at", String(19), nullable=False, server_default=text("''")),
    Column("created_at", String(19), nullable=False),
    Column("updated_at", String(19), nullable=False),
    UniqueConstraint("username", name="ux_users_username"),
    Index("idx_users_role_active", "role", "active"),
)

routers = Table(
    "routers",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("name", String(191), nullable=False),
    Column("router_ip", String(191), nullable=False),
    Column("api_port", String(20), nullable=False, server_default=text("'8728'")),
    Column("router_username", String(191), nullable=False),
    Column("router_password", Text, nullable=False),
    Column("status", String(32), nullable=False, server_default=text("'unknown'")),
    Column("last_synced_at", String(19), nullable=False, server_default=text("''")),
    Column("created_at", String(19), nullable=False),
    Column("updated_at", String(19), nullable=False),
    Index("idx_routers_login_id", "router_ip", "api_port", "router_username", "id"),
    Index("idx_routers_name_id", "name", "id"),
)

packages = Table(
    "packages",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="CASCADE"), nullable=False),
    Column("name", String(191), nullable=False),
    Column("rate_limit", String(100), nullable=False, server_default=text("''")),
    Column("validity_period", String(64), nullable=False),
    Column("data_cap", String(64), nullable=False, server_default=text("''")),
    Column("price", Numeric(10, 2), nullable=False, server_default=text("0.00")),
    Column("archived", Integer, nullable=False, server_default=text("0")),
    Column("created_at", String(19), nullable=False),
    Column("updated_at", String(19), nullable=False),
    Index("idx_packages_router_archived", "router_id", "archived"),
    Index("idx_packages_router_name", "router_id", "name"),
)

voucher_batches = Table(
    "voucher_batches",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="CASCADE"), nullable=False),
    Column("prefix", String(32), nullable=False, server_default=text("''")),
    Column("character_set", String(32), nullable=False, server_default=text("'uppercase_numbers'")),
    Column("avoid_ambiguous", Integer, nullable=False, server_default=text("1")),
    Column("quantity", Integer, nullable=False),
    Column("package_id", Integer),
    Column("created_by", Integer),
    Column("pushed_count", Integer, nullable=False, server_default=text("0")),
    Column("failed_count", Integer, nullable=False, server_default=text("0")),
    Column("created_at", String(19), nullable=False),
    Index("idx_batches_router_created", "router_id", "created_at"),
    Index("idx_batches_package_created", "package_id", "created_at"),
)

vouchers = Table(
    "vouchers",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="CASCADE")),
    Column("package_id", Integer),
    Column("batch_id", Integer),
    Column("created_by", Integer),
    Column("username", String(191), nullable=False),
    Column("password", Text, nullable=False),
    Column("profile", String(191), nullable=False),
    Column("time_limit", String(64), nullable=False),
    Column("price", Numeric(10, 2), nullable=False, server_default=text("0.00")),
    Column("data_limit", String(64), nullable=False, server_default=text("''")),
    Column("shared_users", String(16), nullable=False, server_default=text("'1'")),
    Column("status", String(32), nullable=False, server_default=text("'unused'")),
    Column("comment", Text),
    Column("expiry_date", String(32), nullable=False, server_default=text("''")),
    Column("activated_at", String(19), nullable=False, server_default=text("''")),
    Column("expires_at", String(19), nullable=False, server_default=text("''")),
    Column("removed_at", String(19), nullable=False, server_default=text("''")),
    Column("last_error", Text),
    Column("retry_count", Integer, nullable=False, server_default=text("0")),
    Column("first_login_mac", String(64), nullable=False, server_default=text("''")),
    Column("first_login_ip", String(64), nullable=False, server_default=text("''")),
    Column("device_name", String(191), nullable=False, server_default=text("''")),
    Column("uptime_used", String(64), nullable=False, server_default=text("''")),
    Column("data_used", String(64), nullable=False, server_default=text("''")),
    Column("online_users", Integer, nullable=False, server_default=text("0")),
    Column("routeros_id", String(191)),
    Column("created_at", String(19), nullable=False),
    Column("updated_at", String(19), nullable=False),
    UniqueConstraint("router_id", "username", name="ux_vouchers_router_username"),
    Index("idx_vouchers_router_created_id", "router_id", "created_at", "id"),
    Index("idx_vouchers_router_status_created_id", "router_id", "status", "created_at", "id"),
    Index("idx_vouchers_router_status_expires", "router_id", "status", "expires_at"),
    Index("idx_vouchers_router_package_status", "router_id", "package_id", "status"),
    Index("idx_vouchers_router_profile_created_id", "router_id", "profile", "created_at", "id"),
)

sales = Table(
    "sales",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("voucher_id", Integer, ForeignKey("vouchers.id", ondelete="CASCADE"), nullable=False),
    Column("cashier_id", Integer),
    Column("amount", Numeric(10, 2), nullable=False, server_default=text("0.00")),
    Column("payment_method", String(64), nullable=False, server_default=text("'Cash'")),
    Column("timestamp", String(19), nullable=False),
    UniqueConstraint("voucher_id", name="ux_sales_voucher_id"),
    Index("idx_sales_timestamp", "timestamp"),
    Index("idx_sales_cashier_timestamp", "cashier_id", "timestamp"),
)

audit_logs = Table(
    "audit_logs",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("actor_user_id", Integer),
    Column("router_id", Integer),
    Column("entity_type", String(64), nullable=False),
    Column("entity_id", Integer),
    Column("action", String(64), nullable=False),
    Column("message", Text),
    Column("created_at", String(19), nullable=False),
    Index("idx_audit_router_created", "router_id", "created_at"),
)

reconciliation_issues = Table(
    "reconciliation_issues",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="CASCADE"), nullable=False),
    Column("issue_type", String(64), nullable=False),
    Column("remote_name", String(191), nullable=False),
    Column("routeros_id", String(191), nullable=False, server_default=text("''")),
    Column("details", Text),
    Column("status", String(32), nullable=False, server_default=text("'open'")),
    Column("occurrence_count", Integer, nullable=False, server_default=text("1")),
    Column("first_seen_at", String(19), nullable=False),
    Column("last_seen_at", String(19), nullable=False),
    Column("resolved_at", String(19), nullable=False, server_default=text("''")),
    UniqueConstraint("router_id", "issue_type", "remote_name", name="ux_reconciliation_issue_key"),
    Index("idx_reconciliation_router_status", "router_id", "status", "last_seen_at"),
)

wireguard_interfaces = Table(
    "wireguard_interfaces",
    METADATA,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("interface_name", String(191), nullable=False),
    Column("private_key", Text, nullable=False),
    Column("public_key", Text, nullable=False),
    Column("listen_port", Integer, nullable=False, server_default=text("51820")),
    Column("address", String(191), nullable=False),
    Column("mtu", Integer, nullable=False, server_default=text("1420")),
    Column("notes", Text),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="SET NULL")),
    Column("created_at", String(19), nullable=False),
    Index("idx_wireguard_interface_name", "interface_name"),
    Index("idx_wireguard_created_at", "created_at"),
)

router_sessions = Table(
    "router_sessions",
    METADATA,
    Column("token", String(191), primary_key=True),
    Column("user_id", Integer),
    Column("router_id", Integer, ForeignKey("routers.id", ondelete="CASCADE"), nullable=False),
    Column("router_ip", String(191), nullable=False),
    Column("api_port", String(20), nullable=False),
    Column("router_username", String(191), nullable=False),
    Column("router_password", Text, nullable=False),
    Column("expires_at", Float, nullable=False),
    Column("created_at", String(19), nullable=False),
    Column("updated_at", String(19), nullable=False),
    Index("idx_router_sessions_user_expires", "user_id", "expires_at"),
)

router_login_attempts = Table(
    "router_login_attempts",
    METADATA,
    Column("id", BigInteger, primary_key=True, autoincrement=True),
    Column("client_key", String(64), nullable=False),
    Column("attempted_at", Float, nullable=False),
    Column("success", Integer, nullable=False, server_default=text("0")),
    Index("idx_router_login_attempts_client_time", "client_key", "attempted_at"),
)
